Repository thoth-station/core, pull requests merged in 2018-09, with the labels that each got.

#139 Create provenance checker template when provisioning
  playbooks/roles/thoth-backend/tasks/main.yaml
Labels: approved, size/XS

#143 added metrics url configmap entry
  Jenkinsfile
  openshift/configmap-template.yaml
Labels: size/L

#145 Fix missing label to correctly deprovision thoth
  playbooks/roles/thoth-infra-buildconfigs/tasks/main.yaml
Labels: approved, size/XS

#146 Update README file
  README.rst
Labels: approved, size/L

#147 Use reStructuredText instead of Markdown
  doc/code-review.md
  doc/code-review.rst
  doc/development-good-practice.md
  doc/development-good-practice.rst
  doc/naming-schema.md
  doc/naming-schema.rst
  doc/operations.md
  doc/operations.rst
  doc/release-management.md
  doc/release-management.rst
Labels: approved, size/L
