Repository thoth-station/core, pull requests merged in 2018-04, with the labels that each got.

#3 this is template cleanup and jenkins pipeline
  .gitignore
  Jenkinsfile
  README.rst
  openshift/conf.sh
  openshift/configmap-template.yaml
  openshift/deploy.sh
  openshift/secret-template.yaml
  openshift/template.yaml
  playbooks/provision.yaml
  playbooks/roles/provision-thoth-core/tasks/main.yaml
  playbooks/roles/validate-thoth-core/tasks/main.yaml
  playbooks/validate.yaml
Labels: enhancement

#21 placing the pieces in the right spaces
  openshift/template.yaml
  playbooks/provision.yaml
  playbooks/roles/provision-thoth-core/tasks/main.yaml
  playbooks/roles/validate-thoth-core/tasks/main.yaml
Labels: approved

#25 Issue/6
  .gitignore
  openshift/secret-template.yaml
  openshift/template.yaml
  playbooks/provision.yaml
  playbooks/roles/provision-thoth-core/tasks/main.yaml
  playbooks/roles/provision-thoth-frontend/tasks/main.yaml
  playbooks/roles/validate-thoth-core/tasks/main.yaml
Labels: approved

#26 added docker.io as fallback for centos
  playbooks/roles/provision-thoth-frontend/tasks/main.yaml
Labels: approved

#6 Respect logging configuration in env variables
  openshift/configmap-template.yaml
  openshift/template.yaml
Labels: approved

#27 separated out all the tiers
  openshift/sesheta-github-access-token.yaml
  playbooks/provision.yaml
  playbooks/roles/thoth-backend/tasks/main.yaml
  playbooks/roles/thoth-core/tasks/main.yaml
  playbooks/roles/thoth-frontend/tasks/main.yaml
  playbooks/roles/thoth-jenkins/tasks/main.yaml
  playbooks/roles/thoth-middletier/tasks/main.yaml
  playbooks/roles/validate-thoth/tasks/main.yaml
  playbooks/validate.yaml
Labels: approved

#29 This is the Cyborg Team Members
  bots/CHANGELOG.md
  bots/Pipfile
  bots/Pipfile.lock
  bots/README.md
  bots/approve.py
  bots/check_if_labels_present.py
  bots/config.yaml
  bots/merge_pr.py
  bots/openshift/buildConfig-template.yaml
  bots/openshift/cronJob-template.yaml
  bots/playbooks/deploy-sesheta-cronjobs.yaml
  bots/playbooks/roles/sesheta-cronjob/tasks/main.yaml
  bots/sesheta/__init__.py
  bots/sesheta/common.py
  doc/release-management.md
Labels: approved

#31 Create result API build config
  playbooks/roles/thoth-middletier/tasks/main.yaml
Labels: approved, size/XS

#34 Cleanup job needs middletier namespace env variable
  openshift/template.yaml
Labels: approved, size/XS

#40 Feature: End-to-End Tests
  Pipfile
  Pipfile.lock
  features/analyse_container_image.feature
  features/environment.py
  features/result_api.feature
  features/steps/result_api_steps.py
  features/steps/user_api_steps.py
  openshift/buildConfig-e2e-test-template.yaml
  tox.ini
Labels: approved, size/XL

#30 Feature/bots webhooks
  OWNERS
  bots/Pipfile
  bots/Pipfile.lock
  bots/README.md
  bots/config.yaml
  bots/config/config.yaml
  bots/config/plugins.yaml
  bots/merge_pr.py
  bots/openshift/cronJob-template.yaml
  bots/openshift/hook.yaml
  bots/playbooks/deploy-sesheta-cronjobs.yaml
  bots/playbooks/roles/sesheta-cronjob/tasks/main.yaml
  bots/sesheta/common.py
Labels: approved, size/XL

#42 a little consolidation
  playbooks/roles/thoth-core/tasks/main.yaml
Labels: approved, size/M

#44 added based on a conversation on mattermost
  doc/naming-schema.md
Labels: approved, size/S

#43 Fix deployment
  playbooks/roles/thoth-core/tasks/main.yaml
  playbooks/roles/thoth-frontend/tasks/main.yaml
Labels: approved, size/M

#47 Remove thoth- prefix
  playbooks/roles/thoth-frontend/tasks/main.yaml
  playbooks/roles/thoth-middletier/tasks/main.yaml
  playbooks/roles/validate-thoth/tasks/main.yaml
Labels: approved, size/S

#46 Make deployment more generic
  playbooks/provision.yaml
  playbooks/validate.yaml
Labels: approved, size/S

#51 added two more repos
  bots/config.yaml
Labels: approved, size/XS

#52 maintaining the bots...
  bots/config.yaml
  bots/config/plugins.yaml
Labels: approved, size/M

#56 adding the misc repository
  bots/config.yaml
  bots/config/plugins.yaml
Labels: approved, size/S

#58 added a role to import required imagestreams
  playbooks/provision.yaml
  playbooks/roles/thoth-backend/tasks/main.yaml
  playbooks/roles/thoth-core-imagestreams/tasks/main.yaml
Labels: approved, lgtm, size/M

#59 added 1/3 of the Naming Service feature
  features/naming_service.feature
  features/steps/naming_service_steps.py
Labels: approved, size/M

#60 added component labels
  bots/config.yaml
Labels: approved, size/S

#62 bounced version, a little less verbose output, more labels
  bots/check_if_labels_present.py
  bots/config.yaml
  bots/sesheta/__init__.py
  bots/sesheta/common.py
Labels: approved, size/S
