Repository thoth-station/core, pull requests merged in 2018-07, with the labels that each got.

#105 updated the ansible-playbook functionality
  .git_init/hooks/pre-commit
  .git_init/hooks/pre-push
  git-clone-repos.yaml
Labels: approved, size/L

#106 merge notifications
  bots/CHANGELOG.md
  bots/merge_pr.py
  bots/openshift/cronJob-template.yaml
  bots/sesheta/__init__.py
Labels: approved, size/M

#103 Sesheta is no longer SrcOps'ing thoth/storages
  bots/config.yaml
  bots/config/plugins.yaml
Labels: approved, size/S

#107 merger metrics
  bots/CHANGELOG.md
  bots/Pipfile
  bots/Pipfile.lock
  bots/merge_pr.py
  bots/openshift/buildConfig-template.yaml
  bots/openshift/cronJob-template.yaml
  bots/openshift/hook.yaml
  bots/sesheta/__init__.py
Labels: approved, size/L

#84 Fixing errors in e2e test
  features/analyse_container_image.feature
  features/naming_service.feature
  features/result_api.feature
  features/steps/result_api_steps.py
  features/steps/user_api_steps.py
Labels: approved, size/L

#98 Add missing imagestreams
  playbooks/roles/thoth-core/tasks/main.yaml
Labels: approved, size/XS

#115 Adviser deployment configuration
  playbooks/roles/thoth-backend/tasks/main.yaml
  playbooks/roles/thoth-core-imagestreams/tasks/main.yaml
  playbooks/roles/thoth-core/tasks/main.yaml
  playbooks/roles/thoth-infra-buildconfigs/tasks/main.yaml
Labels: approved

#116 Provision adviser build config
  playbooks/roles/thoth-backend/tasks/main.yaml
Labels: approved

#118 Expose infra namespace name in configmap
  openshift/configmap-template.yaml
  playbooks/roles/thoth-backend/tasks/main.yaml
  playbooks/roles/thoth-frontend/tasks/main.yaml
  playbooks/roles/thoth-middletier/tasks/main.yaml
Labels: approved

#119 Add solver and package extract pod templates
  playbooks/roles/thoth-middletier/tasks/main.yaml
Labels: approved

#117 internal registry setup
  bots/openshift/buildConfig-template.yaml
  bots/openshift/daily_standup-template.yaml
  playbooks/bootstrap_stage_upshift.yaml
  playbooks/deprovision.yaml
  playbooks/provision.yaml
  playbooks/roles/thoth-frontend/tasks/main.yaml
Labels: approved, enhancement

#123 Provision missing parts
  playbooks/roles/thoth-backend/tasks/main.yaml
  playbooks/roles/thoth-core/tasks/main.yaml
  playbooks/roles/thoth-infra-buildconfigs/tasks/main.yaml
  playbooks/roles/thoth-middletier/tasks/main.yaml
Labels: approved

#120 Remove unused configuration options from configmap
  openshift/configmap-template.yaml
Labels: approved

#125 Add missing configmap parameter
  openshift/configmap-template.yaml
Labels: approved

#128 noted a few thought re ops, template, labels down
  doc/operations.md
Labels: approved, enhancement

#124 Make CronJob suspend configurable
  playbooks/provision.yaml
  playbooks/roles/thoth-frontend/tasks/main.yaml
Labels: approved

#130 Deployment fixes
  openshift/template.yaml
  playbooks/roles/thoth-frontend/tasks/main.yaml
  playbooks/roles/thoth-infra-buildconfigs/tasks/main.yaml
Labels: approved

#129 Adjust deprovision playbook
  README.rst
  playbooks/deprovision.yaml
Labels: approved
