Repository thoth-station/core, pull requests merged in 2018-06, with the labels that each got.

#76 Rename THOTH_MIDDLEEND_NAMESPACE to THOTH_MIDDLETIER_NAMESPACE
  README.rst
  openshift/configmap-template.yaml
  openshift/template.yaml
  playbooks/provision.yaml
  playbooks/roles/thoth-backend/tasks/main.yaml
  playbooks/roles/thoth-frontend/tasks/main.yaml
  playbooks/roles/thoth-middletier/tasks/main.yaml
  playbooks/validate.yaml
Labels: approved, lgtm, size/M

#79 Rename THOTH_CEPH_HOST to THOTH_S3_ENDPOINT_URL
  openshift/configmap-template.yaml
  openshift/manual-graph-sync-job.yaml
  playbooks/bootstrap_stage_upshift.yaml
  playbooks/provision.yaml
  playbooks/roles/thoth-backend/tasks/main.yaml
  playbooks/roles/thoth-frontend/tasks/main.yaml
  playbooks/roles/thoth-middletier/tasks/main.yaml
Labels: approved, lgtm, size/S

#83 ansible cleanup imagestreams
  bots/Pipfile
  bots/Pipfile.lock
  bots/daily_standup.py
  playbooks/provision.yaml
  playbooks/roles/thoth-core/tasks/main.yaml
Labels: approved, size/L

#86 documentation of git hooks
  doc/development-good-practice.md
Labels: approved, size/M

#92 added the pipelines to the core queue
  .zuul.yaml
Labels: size/S

#93 adding a few things missed and a new feature
  .zuul.yaml
  CHANGELOG.md
  VERSION
Labels: size/S

#88 Added the prometheus pushgateway host and port env vars
  openshift/configmap-template.yaml
  playbooks/provision.yaml
  playbooks/roles/thoth-frontend/tasks/main.yaml
  playbooks/roles/thoth-middletier/tasks/main.yaml
Labels: approved, needs-rebase, size/S

#95 ansible playbooks for cloning repos and updating repos
  git-clone-repos.yaml
  git-update-repos.yaml
Labels: approved, size/L

#102 sesheta is no longer merging on kebechet repository
  .travis.yml
  bots/config.yaml
Labels: approved, size/XS

#100 Fix template space causing errors during deployment
  playbooks/roles/thoth-backend/tasks/main.yaml
  playbooks/roles/thoth-frontend/tasks/main.yaml
  playbooks/roles/thoth-middletier/tasks/main.yaml
Labels: approved, size/XS

#101 Make Prometheus optional
  openshift/configmap-template.yaml
Labels: approved, size/XS

#104 catching exceptions from github now...
  bots/merge_pr.py
Labels: approved, size/S

#96 Remove trailing whitespace
  playbooks/provision.yaml
Labels: approved, size/XS
