Repository thoth-station/core, pull requests merged in 2018-10, with the labels that each got.

#152 added a grafana dashboard for graph syns job metrics
  grafana/thoth_services.json
Labels: size/XL

#150 Make Sentry DSN configurable on deployment
  openshift/configmap-template.yaml
  playbooks/provision.yaml
Labels: approved, size/S, size/XS

#151 Provision dependency monkey template
  playbooks/roles/thoth-middletier/tasks/main.yaml
Labels: approved, size/XS

#158 Adjust roles to point to correct files
  playbooks/roles/thoth-backend/tasks/main.yaml
  playbooks/roles/thoth-middletier/tasks/main.yaml
Labels: approved, size/S

#156 fixed the config map to carry janusgraph info
  openshift/buildConfig-e2e-test-template.yaml
  openshift/configmap-template.yaml
  playbooks/bootstrap_stage_upshift.yaml
  playbooks/provision.yaml
  playbooks/roles/thoth-core/tasks/main.yaml
Labels: approved, size/L

#157 moved the sentry sdn into the secret rather than the config
  openshift/configmap-template.yaml
  openshift/secret-template.yaml
  playbooks/create_configmap_and_secret.yaml
  playbooks/roles/thoth-backend/tasks/main.yaml
  playbooks/roles/thoth-frontend/tasks/main.yaml
  playbooks/roles/thoth-middletier/tasks/main.yaml
Labels: approved, size/L, size/M

#159 fixing external janusgraph
  README.rst
  doc/operations.rst
  playbooks/create_external_service_janusgraph.yaml
  requirements.yaml
Labels: size/S

#126 removed due to inactivity or migration to sesheta/
  bots/check_if_labels_present.py
  bots/merge_pr.py
  bots/openshift/cronJob-template.yaml
Labels: approved, size/L

#162 Feature/configurable external janusgraph
  .gitignore
  README.rst
  openshift/configmap-template.yaml
  playbooks/bootstrap_stage_upshift.yaml
  playbooks/create_configmap_and_secret.yaml
  playbooks/create_external_service_janusgraph.yaml
  playbooks/deprovision.yaml
  playbooks/group_vars/all/vars
  playbooks/group_vars/all/vault
  playbooks/provision.yaml
  playbooks/roles/thoth-backend/tasks/main.yaml
  playbooks/roles/thoth-core-imagestreams/tasks/main.yaml
  playbooks/roles/thoth-frontend/tasks/main.yaml
  playbooks/roles/thoth-infra-buildconfigs/tasks/main.yaml
  playbooks/roles/thoth-middletier/tasks/main.yaml
  requirements.yaml
Labels: approved, size/L

#160 revisited provisioning
  .gitignore
  README.rst
  playbooks/bootstrap_stage_upshift.yaml
  playbooks/create_configmap_and_secret.yaml
  playbooks/create_external_service_janusgraph.yaml
  playbooks/deprovision.yaml
  playbooks/group_vars/all/vars
  playbooks/group_vars/all/vault
  playbooks/provision.yaml
  playbooks/roles/thoth-backend/tasks/main.yaml
  playbooks/roles/thoth-core-imagestreams/tasks/main.yaml
  playbooks/roles/thoth-frontend/tasks/main.yaml
  playbooks/roles/thoth-infra-buildconfigs/tasks/main.yaml
  playbooks/roles/thoth-middletier/tasks/main.yaml
  requirements.yaml
Labels: size/L

#163 some minor changes to the provision playbook
  playbooks/group_vars/all/vars
  playbooks/provision.yaml
Labels: approved, size/S

#173 Delete validate.yaml
  playbooks/validate.yaml
Labels: size/S
