Repository thoth-station/core, pull requests merged in 2018-05, with the labels that each got.

#63 added notebook as a component
  bots/config.yaml
Labels: approved, size/XS

#64 DevOps: reset component to stable build
  bots/CHANGELOG.md
  bots/README.md
  bots/openshift/buildConfig-template.yaml
  bots/openshift/cronJob-template.yaml
  bots/openshift/hook.yaml
  bots/playbooks/reset_buildpipeline.yaml
  bots/sesheta/__init__.py
Labels: approved, component/bots, size/M

#66 some adoptions...
  bots/config/plugins.yaml
  openshift/template.yaml
  playbooks/bootstrap_stage_upshift.yaml
  playbooks/roles/thoth-backend/tasks/main.yaml
  playbooks/roles/thoth-core/tasks/main.yaml
  playbooks/roles/thoth-frontend/tasks/main.yaml
  playbooks/roles/thoth-infra-buildconfigs/tasks/main.yaml
  playbooks/roles/thoth-jenkins/tasks/main.yaml
  playbooks/roles/thoth-middletier/tasks/main.yaml
Labels: approved, size/L

#68 Fix deployment - oc tag has no confirm option
  playbooks/roles/thoth-core-imagestreams/tasks/main.yaml
Labels: approved, size/XS

#71 Add rsyslog configuration for logging
  openshift/configmap-template.yaml
Labels: approved, lgtm

#70 Apply buildconfigs on deployment
  playbooks/provision.yaml
Labels: approved, size/XS

#72 Add missing rsyslog entries to configmap
  openshift/configmap-template.yaml
Labels: approved, size/XS

#73 added kebechet to the bots
  bots/config.yaml
  bots/config/plugins.yaml
Labels: approved, size/S

#74 added the 'bot' label
  bots/config.yaml
Labels: approved, size/XS
