Repository thoth-station/core, pull requests merged in 2018-11, with the labels that each got.

#178 removed the unused jenkins role
  playbooks/roles/thoth-jenkins/tasks/main.yaml
Labels: approved, size/S

#177 added amun provisioning
  playbooks/group_vars/all/vars
  playbooks/provision.yaml
  requirements.yaml
Labels: approved, size/S

#176 some playbook cleanup
  playbooks/deprovision.yaml
  playbooks/group_vars/all/vault
  playbooks/provision.yaml
Labels: approved, size/M

#175 Add a dummy .vault_pass for user
  .vault_pass
Labels: approved, size/XS

#180 added management api key
  openshift/secret-template.yaml
Labels: approved, size/M

#182 Update janusgraph environment variables
  openshift/manual-graph-sync-job.yaml
Labels: approved, size/XS
