Repository thoth-station/core, pull requests merged in 2019-04, with the labels that each got.

#211 fixed the ISIS_API_URL parameter name
  openshift/configmap-template.yaml
Labels: approved, size/XS

#212 Remove manual graph sync job template
  openshift/manual-graph-sync-job.yaml
Labels: approved, size/M

#215 [WIP] added ConfigMap entries required for Dgraph
  openshift/configmap-template.yaml
Labels: approved, size/S

#216 Dgraph configuration adjustments
  openshift/configmap-template.yaml
Labels: approved, size/XS
