Repository thoth-station/core, pull requests merged in 2019-02, with the labels that each got.

#191 Update architecture diagram
  doc/architecture.dia
  doc/architecture.png
Labels: size/XS

#192 Place build-watcher into amun-api namespace
  doc/architecture.dia
  doc/architecture.png
Labels: size/XS

#193 Update year in sources
  bots/daily_standup.py
  bots/sesheta/__init__.py
  bots/sesheta/common.py
  features/steps/naming_service_steps.py
  features/steps/result_api_steps.py
  features/steps/user_api_steps.py
Labels: size/L, size/XS

#196 Fix inspection specific parts placement
  doc/architecture.dia
  doc/architecture.png
Labels: approved, size/XS

#198 Minor fixes in schema
  doc/architecture.dia
  doc/architecture.png
Labels: size/XS

#197 Add note to Amun API url for clarification
  openshift/configmap-template.yaml
Labels: size/XS

#199 updates to reflect changes in all the components
  playbooks/group_vars/all/vars
  playbooks/group_vars/all/vault
  playbooks/provision.yaml
Labels: size/L

#195 addressing CVEs and relocked
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#194 addressing CVE-2017-18342 and CVE-2018-18074
  bots/Pipfile
  bots/Pipfile.lock
Labels: approved, size/L

#201 create the BC and IS correctly
  playbooks/provision.yaml
Labels: approved, size/XS
