Repository thoth-station/core, pull requests merged in 2020-11, with the labels that each got.

#245 using Markdown Architectural Decision Records
  README.rst
  docs/adr/0000-use-markdown-architectural-decision-records.md
  docs/adr/0001-use-gpl3-as-license.md
  docs/adr/template.md
Labels: hacktoberfest-accepted, size/L

#247 add release policy ADR
  docs/adr/0002-release-policy.md
Labels: approved, size/M

#248 add section on nb-reqs to ROADMAP document
  docs/ROADMAP.md
Labels: approved, kind/feature, size/XS

#249 Improve doc on Jupyter tools
  docs/ROADMAP.md
Labels: approved, size/S

#257 Add links to join Thoth demo sessions and chat
  README.rst
Labels: approved, size/S
