Repository thoth-station/core, pull requests merged in 2021-12, with the labels that each got.

#340 add text2prescription intern project
  docs/intern-projects/generate-prescription-from-text.md
Labels: approved, size/M

#362 Update github-config.yaml
  community/github-config.yaml
Labels: approved, size/XS

#351 Update the generator app
  community/generator/app.go
  community/generator/app_test.go
Labels: approved, size/L

#354 Document SIG User Experience
  OWNERS_ALIASES
  community/liaisons.md
  community/sig-list.md
  community/sig-user-experience/OWNERS
  community/sig-user-experience/README.md
  community/sig-user-experience/charter.md
  community/sigs.yaml
Labels: approved, size/L
