Repository thoth-station/core, pull requests merged in 2021-07, with the labels that each got.

#298 feat: Bootstrap Thoth-Station for peribolos
  .github/ISSUE_TEMPLATE/membership.md
  .github/ISSUE_TEMPLATE/membership.yaml
  .github/ISSUE_TEMPLATE/repo-archive.md
  .github/ISSUE_TEMPLATE/repo-archive.yaml
  .github/ISSUE_TEMPLATE/repo-create.md
  .github/ISSUE_TEMPLATE/repo-create.yaml
  .prow.yaml
  community/labels.md
  community/labels.md.tmpl
  community/labels.yaml
Labels: approved, size/XL

#301 Add intern project for Viliam
  docs/intern-projects/detecting-lincenses-of-python-modules.md
Labels: approved, size/M

#299 remove init playbooks
  .git_init/hooks/pre-commit
  .git_init/hooks/pre-push
  .gitignore
  .pre-commit-config.yaml
  README.rst
  community/github-config.yaml
  git-clone-repos.yaml
  git-update-repos.yaml
Labels: approved, lgtm, size/L

#302 add support repo and a few labels for it
  community/github-config.yaml
  community/labels.yaml
Labels: approved, lgtm, size/S

#303 fix some prescriptions related configs
  community/github-config.yaml
Labels: approved, size/XS

#288 Removed TODO
  community/generator/app.go
Labels: approved, size/M

#307 add moldavite api
  .github/ISSUE_TEMPLATE/.config.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
  .github/PULL_REQUEST_TEMPLATE.md
  community/github-config.yaml
Labels: approved, size/M

#305 Add project description to bootstrap prescription database
  docs/intern-projects/prescriptions-bootstrap.md
Labels: approved, size/M
