Repository thoth-station/core, pull requests merged in 2021-04, with the labels that each got.

#267 release 2021.04.12
  .thoth.yaml
  README.rst
  RELEASES.md
  community/labels.md
  docs/TermsAndConditionsForTheScrum.md
Labels: do-not-merge/hold, size/L

#268 Update code-review.rst
  docs/code-review.rst
Labels: size/XS

#270 Updates based on the ci changes
  .aicoe-ci.yaml
  .git_init/hooks/pre-commit
  .git_init/hooks/pre-push
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
  .pre-commit-config.yaml
  .prow.yaml
  .thoth.yaml
  README.rst
  community/Makefile
  community/generator/app.go
  community/generator/app_test.go
  community/generator/committee_readme.tmpl
  community/generator/sig_readme.tmpl
  community/labels.md
  community/sig-docs/OWNERS
  community/sig-docs/charter.md
  community/sig-pipelines/OWNERS
  community/sig-pipelines/charter.md
  docs/adr/0001-use-gpl3-as-license.md
  docs/adr/0002-release-policy.md
  docs/adr/template.md
  docs/operations.rst
  docs/repository_directory_layout.rst
  docs/sprint-demos/35.md
  docs/sprint-demos/38.md
  docs/sprint-demos/README.md
  fdl-1.3.txt
  git-clone-repos.yaml
  git-update-repos.yaml
Labels: approved, size/XXL

#273 Update app.go
  community/generator/app.go
Labels: approved, size/XS

#274 Add sig-observability and update sig list
  OWNERS_ALIASES
  community/liaisons.md
  community/sig-list.md
  community/sig-observability/OWNERS
  community/sig-observability/README.md
  community/sig-observability/charter.md
  community/sigs.yaml
Labels: approved, size/L
