Repository thoth-station/core, pull requests merged in 2021-05, with the labels that each got.

#280 add a ARD to retire Qeb-Hwt
  docs/adr/0003-decommision-qeb-hwt.md
Labels: approved, size/S

#278 add a code of conduct
  CODE_OF_CONDUCT.md
Labels: lgtm, size/M

#282 update the prow resource limits
  .prow.yaml
Labels: approved, size/XS
