Repository thoth-station/core, pull requests merged in 2021-06, with the labels that each got.

#279 add a contributing doc
  CONTRIBUTING.md
Labels: size/M

#285 Add solver classifier intern project description
  docs/intern-projects/Inferring-package-names-out-of-Python-imports.md
  docs/intern-projects/classify-errors-produced-during-installation-of-python-modules.md
Labels: approved, size/M

#291 add pulp repo
  .github/ISSUE_TEMPLATE/membership.md
  .github/ISSUE_TEMPLATE/repo-archive.md
  .github/ISSUE_TEMPLATE/repo-create.md
  .prow.yaml
  community/OWNERS
  community/github-config.yaml
  community/labels.md
Labels: approved, size/S

#293 add ps-nlp and ps-cv
  community/github-config.yaml
Labels: approved, size/S

#295 pulp-repository-sync-job has been renamed
  community/github-config.yaml
Labels: approved, size/XS

#296 Add refs to ADR
  README.rst
Labels: approved, size/XS
