Repository thoth-station/core, pull requests merged in 2022-03, with the labels that each got.

#389 Clean up labels to match current SIGs
  community/labels.md
  community/labels.yaml
Labels: approved, size/M

#388 Remove sig-docs
  OWNERS_ALIASES
  community/OWNERS_ALIASES
  community/liaisons.md
  community/sig-docs/OWNERS
  community/sig-docs/README.md
  community/sig-docs/charter.md
  community/sig-list.md
  community/sigs.yaml
Labels: approved, size/L

#390 Set SP-pipelines meeting to weekly
  community/sig-devsecops/README.md
  community/sig-list.md
  community/sigs.yaml
Labels: approved, size/XS, lgtm

#394 Remove user from devs team
  community/github-config.yaml
Labels: approved, size/XS, lgtm

#381 Introduce an ADR for automatic base image version updates
  docs/adr/0005-automatically-bump-container-image-versions.md
Labels: approved, size/M, lgtm

#395 added oindrillac to thoth members
  community/github-config.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test
