Repository thoth-station/core, pull requests merged in 2022-08, with the labels that each got.

#443 Update github-config.yaml
  community/github-config.yaml
Labels: approved, size/XS, lgtm

#439 ADR for Scorecard metrics aggregation and stack quality scoring
  docs/adr/0007-scorecard-metrics.md
  docs/adr/images/Scorecards_metrics_ADR.png
Labels: approved, size/S

#438 :turtle: Allow sig-chairs with write access to multiple repos
  community/github-config.yaml
Labels: approved, size/L

#447 :pray: Thank you for your service
  community/github-config.yaml
Labels: approved, size/XS

#450 Update ci and code review docs
  docs/code-review.rst
Labels: approved, size/S
