Repository thoth-station/core, pull requests merged in 2022-12, with the labels that each got.

#475 Make myself an org admin
  community/github-config.yaml
Labels: approved, size/XS, lgtm

#478 adding svg version of robot
  images/toth-robot.svg
Labels: approved, size/L, lgtm, kind/feature, priority/important-longterm

#476 add support policy document
  community/SUPPORT_POLICY.md
Labels: approved, size/S, lgtm
