Repository thoth-station/core, pull requests merged in 2022-02, with the labels that each got.

#374 Add stress-tests repo to github config
  community/github-config.yaml
Labels: approved, size/XS

#378 Include pulp metrics exporter
  community/github-config.yaml
Labels: approved, size/XS

#379 Add mi to the subprojects
  community/sig-observability/README.md
Labels: approved, size/XS

#376 Differentiate between files generation and label sync in Makefile
  community/Makefile
  community/README.md
Labels: approved, size/S

#375 Add SIG Stack Guidance
  OWNERS_ALIASES
  community/liaisons.md
  community/sig-list.md
  community/sig-stack-guidance/OWNERS
  community/sig-stack-guidance/README.md
  community/sig-stack-guidance/charter.md
  community/sigs.yaml
Labels: approved, size/XL

#382 SIG DevSecOps: fold sig-pipelines into it and update documentation
  .pre-commit-config.yaml
  .prow.yaml
  OWNERS_ALIASES
  community/labels.md
  community/labels.yaml
  community/liaisons.md
  community/sig-devsecops/README.md
  community/sig-devsecops/charter.md
  community/sig-list.md
  community/sig-pipelines/OWNERS
  community/sig-pipelines/README.md
  community/sig-pipelines/charter.md
  community/sigs.yaml
Labels: approved, size/L

#380 Include new repos in thoth-station and remove old team members
  community/github-config.yaml
Labels: approved, size/M

#387 :exclamation: Peribolos binaries is shifted to /ko-app/ dir
  .prow.yaml
Labels: approved, size/XS, sig/devsecops

#385 Add regular SIG Stack Guidance meeting
  community/sig-list.md
  community/sig-stack-guidance/README.md
  community/sigs.yaml
Labels: approved, size/S, lgtm

#386 Remove needs-triage label by default
  .prow.yaml
  community/labels.md
  community/labels.yaml
Labels: approved, size/M
