Repository thoth-station/core, pull requests merged in 2022-07, with the labels that each got.

#420 Adding VannTen (Max Gautier) as project member
  community/github-config.yaml
Labels: approved, size/XS, ok-to-test

#421 Update SIG-UserExperience details
  OWNERS_ALIASES
  community/sig-list.md
  community/sig-user-experience/README.md
  community/sigs.yaml
Labels: approved, size/S, lgtm

#428 Fix a typo
  docs/TermsAndConditionsForTheScrum.md
Labels: approved, size/XS

#429 Enable repository projects for thoth-station organisation
  community/github-config.yaml
Labels: approved, size/XS, lgtm

#435 Clarify documentation about issue triage
  docs/TermsAndConditionsForTheScrum.md
Labels: approved, size/XS, lgtm
