Repository thoth-station/core, pull requests merged in 2022-06, with the labels that each got.

#413 Add shreekarSS to thoth members
  community/github-config.yaml
Labels: do-not-merge/hold

#393 ADR for kebechet optimization
  docs/adr/0005-obtimizing-keb-runs.md
Labels: size/M, lifecycle/stale

#410 ADR proposal for the Thoth GitHub Action
  docs/adr/0006-thoth-github-action.md
  docs/adr/images/Thoth-GitHub-Action-ADR.drawio.png
Labels: approved, size/M, lgtm

#416 HouseKeeping: Updated repos and teams for triaging
  OWNERS
  community/github-config.yaml
Labels: approved, size/L

#418 Enable projects for thoth-station/support && thoth-station/srcops-testing
  community/github-config.yaml
Labels: approved, size/XS, lgtm
