Repository thoth-station/core, pull requests merged in 2022-05, with the labels that each got.

#403 Add @4n4nd and @Shreyanand as thoth-station org members
  community/github-config.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#407 Make peribolos and label_sync use ghproxy
  .prow.yaml
Labels: approved, size/S

#399 Update the Terms and Conditions for the Scrum document
  docs/ROADMAP.md
  docs/TermsAndConditionsForTheScrum.md
Labels: approved, size/L

#405 removing pacospace :(
  community/github-config.yaml
Labels: approved, size/XS

#409 [prow] Fix label_sync token argument name
  .prow.yaml
  community/labels.yaml
Labels: approved, size/XS
