Repository thoth-station/core, pull requests merged in 2022-01, with the labels that each got.

#364 Make GitHub issue templates a bit more friendly
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/M

#368 Setup a dedicated meetup slot for Thoth observability
  community/sig-list.md
  community/sig-observability/README.md
  community/sigs.yaml
Labels: approved, size/S

#367 Introduce the sig devops for thoth-station release
  OWNERS_ALIASES
  community/labels.yaml
  community/liaisons.md
  community/sig-devsecops/OWNERS
  community/sig-devsecops/README.md
  community/sig-devsecops/charter.md
  community/sig-list.md
  community/sigs.yaml
Labels: approved, size/L

#369 Add documentation about labels/sig/repo maintenance
  README.rst
  community/Makefile
  community/README.md
Labels: approved, size/M
